name: CI

on: [push]
jobs:
  build:
    env:
      MEOW: meow
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo meow
    - name: Run a multi-line script
      run: |
        echo $MEOW
        
        mkdir /tmp/logs
        echo meow > /tmp/logs/cat.log

        exit 1
        
