name: CI

on: [push]
jobs:
  build:
    strategy:
      matrix:
        foo: [0, 1]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo ${{matrix.foo}}
    - name: Run a multi-line script
      run: |
        cat /proc/cpuinfo
        ip link
        ip addr
        
        mkdir /tmp/logs
        echo meow > /tmp/logs/cat.log
        
        curl -vvv https://ipv6.icanhazip.com
        
