name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        cat /proc/cpuinfo
        ip link
        ip addr
        
        mkdir /tmp/logs
        echo meow > /tmp/logs/cat.log
        
        curl -vvv https://ipv6.icanhazip.com
    
    - run: sleep 10 && echo woof > /tmp/logs/dog.log
      if: failure()

    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: logs
        path: /tmp/logs 
