name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        cat /proc/cpuinfo
        ip link
        ip addr
        
        mkdir /tmp/logs
        echo meow > /tmp/logs/cat.log
        
        false
    
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: logs2
        path: /tmp/logs 

    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: logs
        path: /tmp/logs 
