name: CI

on: [push]
jobs:
  build:
    strategy:
      matrix:
        foo: [0, 1]
        bar: [yes, no]
    env:
      MEOW: ${{matrix.foo}}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo ${{matrix.foo}}
    - name: Run a multi-line script
      run: |
        echo $MEOW
        
        mkdir /tmp/logs
        echo meow > /tmp/logs/cat.log
        df -h
        sudo eatmydata apt remove --auto-remove -y aspnetcore-* dotnet-* libmono-* mono-* msbuild 
        df -h
