name: Retest Command

on: 
  issue_comment:
    types: [created]

jobs:
  check_comments:
    name: Check comments for /retest
    runs-on: ubuntu-latest
    steps:
      - name: Check for /retest
        id: retest_command
        uses: xt0rted/slash-command-action@v1
        continue-on-error: true
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          command: retest
      - name: Do /retest
        if: ${{ steps.retest_command.outcome == 'success' }}
        run: |
          echo "The command was '${{ steps.retest_command.outputs.command-name }}' with arguments '${{ steps.retest_command.outputs.command-arguments }}'"
          echo <<EOF
          ${{ toJson(github.event) }}
          EOF
